workflows:
  capacitor-android-build:
    name: Spark Android Debug Build
    max_build_duration: 30
    environment:
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build React Web App
        script: npm run build
      - name: Sync Capacitor Android
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk