workflows:
  capacitor-android-build:
    name: Spark Android Debug Build
    max_build_duration: 30
    environment:
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build React Web App
        script: |
          cd frontend
          npm run build
      - name: Sync Capacitor Android
        script: |
          cd frontend
          npx cap sync android
      - name: Build Android APK
        script: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - frontend/android/app/build/outputs/apk/**/*.apk